//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.431
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CerebelloWebRole.Views.Membership.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MembershipStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MembershipStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Cerebello.Views.Membership.Resources.MembershipStrings", typeof(MembershipStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose an Option....
        /// </summary>
        public static string GenderChoose {
            get {
                return ResourceManager.GetString("GenderChoose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female.
        /// </summary>
        public static string GenderFemale {
            get {
                return ResourceManager.GetString("GenderFemale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male.
        /// </summary>
        public static string GenderMale {
            get {
                return ResourceManager.GetString("GenderMale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informações Básicas.
        /// </summary>
        public static string RegistrationBasicInfoHeader {
            get {
                return ResourceManager.GetString("RegistrationBasicInfoHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conta criada com sucesso.
        /// </summary>
        public static string RegistrationCompletedTitle {
            get {
                return ResourceManager.GetString("RegistrationCompletedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Criar minha conta.
        /// </summary>
        public static string RegistrationCreateMyAccount {
            get {
                return ResourceManager.GetString("RegistrationCreateMyAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credenciais de Login.
        /// </summary>
        public static string RegistrationCredentialsHeader {
            get {
                return ResourceManager.GetString("RegistrationCredentialsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;re just 60 seconds away from your new Cerebello You&apos;re just 60 seconds away from your new Cerebello account..
        /// </summary>
        public static string RegistrationHeader {
            get {
                return ResourceManager.GetString("RegistrationHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Textos e vídeos parar tirar todas as suas dúvidas.
        /// </summary>
        public static string RegistrationSideCompleteDocumentationText {
            get {
                return ResourceManager.GetString("RegistrationSideCompleteDocumentationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documentação Completa.
        /// </summary>
        public static string RegistrationSideCompleteDocumentationTitle {
            get {
                return ResourceManager.GetString("RegistrationSideCompleteDocumentationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dispensa treinamento.
        /// </summary>
        public static string RegistrationSideEasyToUseText {
            get {
                return ResourceManager.GetString("RegistrationSideEasyToUseText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fácil de Usar.
        /// </summary>
        public static string RegistrationSideEasyToUseTitle {
            get {
                return ResourceManager.GetString("RegistrationSideEasyToUseTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rápido, preciso e amigável.
        /// </summary>
        public static string RegistrationSideGreatCustomerServiceText {
            get {
                return ResourceManager.GetString("RegistrationSideGreatCustomerServiceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ótimo Atendimento.
        /// </summary>
        public static string RegistrationSideGreatCustomerServiceTitle {
            get {
                return ResourceManager.GetString("RegistrationSideGreatCustomerServiceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seus dados com backups diários.
        /// </summary>
        public static string RegistrationSideSecureAndReliableText {
            get {
                return ResourceManager.GetString("RegistrationSideSecureAndReliableText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seguro e Confiável.
        /// </summary>
        public static string RegistrationSideSecureAndReliableTitle {
            get {
                return ResourceManager.GetString("RegistrationSideSecureAndReliableTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Você está em boas mãos com o Cerebello.
        /// </summary>
        public static string RegistrationSideYouAreInGoodHands {
            get {
                return ResourceManager.GetString("RegistrationSideYouAreInGoodHands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Criar uma Conta.
        /// </summary>
        public static string RegistrationTitle {
            get {
                return ResourceManager.GetString("RegistrationTitle", resourceCulture);
            }
        }
    }
}
